/**
 * T-020 — `duelReducer(state, event): DuelState`: the pure turn-based duel state machine.
 *
 * FROZEN RED suite. The production module `@engine/duel/reducer` is intentionally absent until
 * the Implementation Agent greens these criteria. Do not edit this file after freeze.
 *
 * Enumeration rule (AC-24 / DoD): phase and event lists below are **hardcoded string literals**.
 * Never derive them from `DUEL_PHASES` or the `DuelEvent` union — T-022 adds a sixth event, and a
 * derived matrix would silently widen AC-16 instead of failing loudly.
 */
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { getCannon } from '@content/index';
import { templateSchema } from '@content/schemas';
import type { CannonId, IslandId, SkillId, Template } from '@content/schemas';
import { resolveShot, type ShotOutcome } from '@engine/duel/damage';
import { duelReducer } from '@engine/duel/reducer';
import {
  createDuelState,
  type ActionLogEntry,
  type DuelConfig,
  type DuelEvent,
  type DuelState,
  type RivalVolley,
} from '@engine/duel/types';
import { QuestionGenerationError, type Question } from '@engine/questions/types';
import { createRng } from '@engine/rng';
import {
  BASE_BALLS_PER_VOLLEY,
  ENEMY_HULL_BY_ISLAND,
  PERFECT_SHOT_TIMER_FRACTION,
  PLAYER_HULL,
} from '@engine/tuning';

// =============================================================================================
// Literal enumerations — declared HERE, not derived from the module under test (AC-24)
// =============================================================================================

const EXPECTED_PHASES = [
  'countdown',
  'playerChoose',
  'reload',
  'resolvePlayer',
  'rivalTurn',
  'resolveRival',
  'victory',
  'defeat',
] as const;

const EXPECTED_EVENT_TYPES = [
  'CANNON_SELECTED',
  'ANSWER_CHOSEN',
  'TIMER_EXPIRED',
  'ANIMATION_DONE',
  'RIVAL_ACTION',
] as const;

/** In-phase events per the ticket transition table. Anything else is a no-op (AC-16). */
const IN_PHASE_EVENTS: Readonly<
  Record<(typeof EXPECTED_PHASES)[number], readonly (typeof EXPECTED_EVENT_TYPES)[number][]>
> = {
  countdown: ['ANIMATION_DONE'],
  playerChoose: ['CANNON_SELECTED'],
  reload: ['ANSWER_CHOSEN', 'TIMER_EXPIRED'],
  resolvePlayer: ['ANIMATION_DONE'],
  rivalTurn: ['RIVAL_ACTION'],
  resolveRival: ['ANIMATION_DONE'],
  victory: [],
  defeat: [],
};

// =============================================================================================
// Paths / source probes
// =============================================================================================

const TEST_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(TEST_DIR, '../../..');
const OWN_SOURCE = readFileSync(fileURLToPath(import.meta.url), 'utf8');
const TICKET_SOURCE = readFileSync(join(REPO_ROOT, 'tickets/T-020.md'), 'utf8');
const REDUCER_SRC_PATH = join(REPO_ROOT, 'src/engine/duel/reducer.ts');
const DUEL_DIR = join(REPO_ROOT, 'src/engine/duel');

const DEFERRED_WORK_MARKERS = [['TO', 'DO'].join(''), ['FIX', 'ME'].join(''), ['HA', 'CK'].join('')];
const FOCUSED_TEST_PATTERN = new RegExp(
  ['\\b(it|test|describe)\\.(', 'sk', 'ip|on', 'ly)\\b|\\b', 'x', '(it|describe)\\b'].join(''),
);

// =============================================================================================
// Fixtures
// =============================================================================================

const FIXTURE_TEMPLATES: Readonly<Partial<Record<SkillId, readonly Template[]>>> = {
  add_within_10: [
    templateSchema.parse({
      id: 'add_within_10__a_plus_b',
      skill: 'add_within_10',
      text: '{a} + {b} = ?',
      params: { a: [1, 5], b: [1, 5] },
      answerExpr: 'a + b',
      distractors: ['a + b + 1', 'a + b - 1', 'a * b'],
    }),
    templateSchema.parse({
      id: 'add_within_10__b_plus_a',
      skill: 'add_within_10',
      text: '{b} + {a} = ?',
      params: { a: [1, 4], b: [1, 4] },
      answerExpr: 'b + a',
      distractors: ['b + a + 2', 'b + a - 1', 'b * a'],
    }),
  ],
  two_step_add_sub: [
    templateSchema.parse({
      id: 'two_step_add_sub__fixture',
      skill: 'two_step_add_sub',
      text: '{a} + {b} - {c} = ?',
      params: { a: [5, 9], b: [1, 4], c: [1, 3] },
      answerExpr: 'a + b - c',
      distractors: ['a + b - c + 1', 'a + b - c - 1', 'a - b + c'],
      constraints: ['a + b - c > 0'],
    }),
  ],
};

const FIXTURE_QUESTION: Question = {
  templateId: 'add_within_10__a_plus_b',
  skill: 'add_within_10',
  text: '3 + 4 = ?',
  params: { a: 3, b: 4 },
  choices: [
    { value: 7, label: '7' },
    { value: 8, label: '8' },
    { value: 6, label: '6' },
    { value: 12, label: '12' },
  ],
  correctIndex: 0,
  isWordProblem: false,
  readAloud: false,
};

const PLAYER_LOADOUT: readonly CannonId[] = Object.freeze<CannonId[]>(['swivel_gun', 'double_broadside']);
const RIVAL_LOADOUT: readonly CannonId[] = Object.freeze<CannonId[]>(['six_pounder', 'chain_shot']);

/** Seed proven (offline via generateQuestion+resolveShot) to sink port_sumwich hull in exactly 4 perfect swivel volleys with rival misses between. */
const SCRIPTED_DUEL_SEED = 0;
const PERFECT_ELAPSED_MS = 1000;
const RIVAL_MISS_ELAPSED_MS = 5000;

function baseConfig(seed: number = 11): DuelConfig {
  return {
    seed,
    islandId: 'port_sumwich' as IslandId,
    playerLoadout: PLAYER_LOADOUT,
    rivalLoadout: RIVAL_LOADOUT,
    templatesBySkill: FIXTURE_TEMPLATES,
  };
}

function sampleEvents(
  cannonId: CannonId = 'swivel_gun',
): Readonly<Record<(typeof EXPECTED_EVENT_TYPES)[number], DuelEvent>> {
  return {
    CANNON_SELECTED: { type: 'CANNON_SELECTED', cannonId },
    ANSWER_CHOSEN: { type: 'ANSWER_CHOSEN', choiceIndex: 0, elapsedMs: 100 },
    TIMER_EXPIRED: { type: 'TIMER_EXPIRED' },
    ANIMATION_DONE: { type: 'ANIMATION_DONE' },
    RIVAL_ACTION: {
      type: 'RIVAL_ACTION',
      volley: { cannonId: 'six_pounder', correct: true, elapsedMs: 800 },
    },
  };
}

const FIXTURE_OUTCOME: ShotOutcome = resolveShot({
  cannon: getCannon('swivel_gun'),
  correct: true,
  elapsedMs: PERFECT_ELAPSED_MS,
  rng: createRng(7),
})[0];

const FIXTURE_VOLLEY: RivalVolley = {
  cannonId: 'six_pounder',
  correct: true,
  elapsedMs: 850,
};

const CORE_BASE = {
  seed: 4242,
  rng: createRng(4242),
  turnToken: 3,
  volleyNumber: 2,
  islandId: 'port_sumwich' as IslandId,
  playerHull: 71,
  enemyHull: 34,
  enemyMaxHull: ENEMY_HULL_BY_ISLAND.port_sumwich,
  playerLoadout: PLAYER_LOADOUT,
  rivalLoadout: RIVAL_LOADOUT,
  recentTemplateIds: ['add_within_10__a_plus_b'] as readonly string[],
  actionLog: [] as readonly ActionLogEntry[],
  tally: {
    correctAnswers: 1,
    totalAnswers: 2,
    perfectShots: 0,
    bySkill: { add_within_10: { correct: 1, attempts: 2 } },
  },
  templatesBySkill: FIXTURE_TEMPLATES,
};

function stateByPhase(): Readonly<Record<(typeof EXPECTED_PHASES)[number], DuelState>> {
  return {
    countdown: { ...CORE_BASE, phase: 'countdown' },
    playerChoose: { ...CORE_BASE, phase: 'playerChoose' },
    reload: {
      ...CORE_BASE,
      phase: 'reload',
      cannonId: 'swivel_gun',
      question: FIXTURE_QUESTION,
      timerMs: getCannon('swivel_gun').timerMs,
    },
    resolvePlayer: {
      ...CORE_BASE,
      phase: 'resolvePlayer',
      cannonId: 'swivel_gun',
      outcome: FIXTURE_OUTCOME,
    },
    rivalTurn: { ...CORE_BASE, phase: 'rivalTurn' },
    resolveRival: {
      ...CORE_BASE,
      phase: 'resolveRival',
      volley: FIXTURE_VOLLEY,
      damageToPlayer: 9,
    },
    victory: {
      ...CORE_BASE,
      phase: 'victory',
      result: { won: true, tally: CORE_BASE.tally, volleys: 2 },
    },
    defeat: {
      ...CORE_BASE,
      phase: 'defeat',
      result: { won: false, tally: CORE_BASE.tally, volleys: 2 },
    },
  };
}

function reloadState(
  overrides: Partial<{
    cannonId: CannonId;
    enemyHull: number;
    playerHull: number;
    question: Question;
    tally: DuelState['tally'];
    actionLog: readonly ActionLogEntry[];
    rng: DuelState['rng'];
    turnToken: number;
    volleyNumber: number;
    recentTemplateIds: readonly string[];
    templatesBySkill: DuelConfig['templatesBySkill'];
  }> = {},
): Extract<DuelState, { phase: 'reload' }> {
  const cannonId = overrides.cannonId ?? 'swivel_gun';
  const cannon = getCannon(cannonId);
  return {
    ...CORE_BASE,
    ...overrides,
    phase: 'reload',
    cannonId,
    question: overrides.question ?? FIXTURE_QUESTION,
    timerMs: cannon.timerMs,
    playerLoadout: PLAYER_LOADOUT,
    rivalLoadout: RIVAL_LOADOUT,
    templatesBySkill: overrides.templatesBySkill ?? FIXTURE_TEMPLATES,
  };
}

function resolvePlayerState(
  overrides: Partial<{
    cannonId: CannonId;
    enemyHull: number;
    playerHull: number;
    outcome: ShotOutcome;
    tally: DuelState['tally'];
    volleyNumber: number;
    turnToken: number;
    actionLog: readonly ActionLogEntry[];
  }> = {},
): Extract<DuelState, { phase: 'resolvePlayer' }> {
  return {
    ...CORE_BASE,
    ...overrides,
    phase: 'resolvePlayer',
    cannonId: overrides.cannonId ?? 'swivel_gun',
    outcome: overrides.outcome ?? FIXTURE_OUTCOME,
    playerLoadout: PLAYER_LOADOUT,
    rivalLoadout: RIVAL_LOADOUT,
  };
}

function rivalTurnState(
  overrides: Partial<{
    playerHull: number;
    enemyHull: number;
    tally: DuelState['tally'];
    actionLog: readonly ActionLogEntry[];
    rng: DuelState['rng'];
    turnToken: number;
    volleyNumber: number;
  }> = {},
): Extract<DuelState, { phase: 'rivalTurn' }> {
  return {
    ...CORE_BASE,
    ...overrides,
    phase: 'rivalTurn',
    playerLoadout: PLAYER_LOADOUT,
    rivalLoadout: RIVAL_LOADOUT,
  };
}

function resolveRivalState(
  overrides: Partial<{
    playerHull: number;
    enemyHull: number;
    volleyNumber: number;
    turnToken: number;
    volley: RivalVolley;
    damageToPlayer: number;
    tally: DuelState['tally'];
    actionLog: readonly ActionLogEntry[];
  }> = {},
): Extract<DuelState, { phase: 'resolveRival' }> {
  return {
    ...CORE_BASE,
    ...overrides,
    phase: 'resolveRival',
    volley: overrides.volley ?? FIXTURE_VOLLEY,
    damageToPlayer: overrides.damageToPlayer ?? 9,
    playerLoadout: PLAYER_LOADOUT,
    rivalLoadout: RIVAL_LOADOUT,
  };
}

function wrongIndex(question: Question): number {
  return (question.correctIndex + 1) % 4;
}

function snapshotArrays(state: DuelState): {
  readonly playerLoadout: readonly CannonId[];
  readonly rivalLoadout: readonly CannonId[];
  readonly recentTemplateIds: readonly string[];
  readonly actionLog: readonly ActionLogEntry[];
  readonly choices: readonly Question['choices'] | undefined;
} {
  return {
    playerLoadout: state.playerLoadout,
    rivalLoadout: state.rivalLoadout,
    recentTemplateIds: state.recentTemplateIds,
    actionLog: state.actionLog,
    choices: state.phase === 'reload' ? state.question.choices : undefined,
  };
}

/** Drive countdown → playerChoose → reload for a loadout cannon. */
function toReload(seed: number, cannonId: CannonId): Extract<DuelState, { phase: 'reload' }> {
  const countdown = createDuelState(baseConfig(seed));
  const choose = duelReducer(countdown, { type: 'ANIMATION_DONE' });
  expect(choose.phase).toBe('playerChoose');
  const reload = duelReducer(choose, { type: 'CANNON_SELECTED', cannonId });
  expect(reload.phase).toBe('reload');
  return reload as Extract<DuelState, { phase: 'reload' }>;
}

/**
 * Scripted victory path for AC-18/19/20: four perfect swivel answers with rival misses between.
 * Seed `SCRIPTED_DUEL_SEED` was selected so enemy hull (45) survives three volleys and sinks on the fourth.
 */
function driveScriptedDuel(): DuelState {
  let state: DuelState = createDuelState(baseConfig(SCRIPTED_DUEL_SEED));

  const apply = (event: DuelEvent): void => {
    state = duelReducer(state, event);
  };

  apply({ type: 'ANIMATION_DONE' }); // → playerChoose

  for (let volley = 1; volley <= 4; volley += 1) {
    apply({ type: 'CANNON_SELECTED', cannonId: 'swivel_gun' });
    expect(state.phase, `volley ${volley} reload`).toBe('reload');
    const reload = state as Extract<DuelState, { phase: 'reload' }>;
    apply({
      type: 'ANSWER_CHOSEN',
      choiceIndex: reload.question.correctIndex,
      elapsedMs: PERFECT_ELAPSED_MS,
    });
    expect(state.phase, `volley ${volley} resolvePlayer`).toBe('resolvePlayer');
    apply({ type: 'ANIMATION_DONE' });

    if (volley < 4) {
      expect(state.phase, `volley ${volley} rivalTurn`).toBe('rivalTurn');
      const hullBeforeRival = state.playerHull;
      apply({
        type: 'RIVAL_ACTION',
        volley: {
          cannonId: 'six_pounder',
          correct: false,
          elapsedMs: RIVAL_MISS_ELAPSED_MS,
        },
      });
      expect(state.phase, `volley ${volley} resolveRival`).toBe('resolveRival');
      // I-3: a standard miss must deal zero player damage (hit-on-miss would still leave the
      // player alive through three volleys and green AC-18 without this check).
      expect(state.playerHull, `volley ${volley} rival miss must not damage player`).toBe(hullBeforeRival);
      expect(state.playerHull).toBe(PLAYER_HULL);
      apply({ type: 'ANIMATION_DONE' });
      expect(state.phase, `volley ${volley} back to playerChoose`).toBe('playerChoose');
      expect(state.playerHull).toBe(PLAYER_HULL);
    }
  }

  return state;
}

// =============================================================================================
// AC-1 — countdown → playerChoose
// =============================================================================================

describe('T-020 duelReducer — phase transitions', () => {
  it('spec(T-020:AC-1) countdown + ANIMATION_DONE → playerChoose and turnToken += 1', () => {
    const start = createDuelState(baseConfig(1));
    expect(start.phase).toBe('countdown');
    expect(start.turnToken).toBe(0);

    const next = duelReducer(start, { type: 'ANIMATION_DONE' });

    expect(next).not.toBe(start);
    expect(next.phase).toBe('playerChoose');
    expect(next.turnToken).toBe(start.turnToken + 1);
  });

  it('spec(T-020:AC-2) CANNON_SELECTED in loadout → reload with question, timer, recent id, advanced rng', () => {
    const choose = duelReducer(createDuelState(baseConfig(2)), { type: 'ANIMATION_DONE' });
    expect(choose.phase).toBe('playerChoose');
    const rngBefore = choose.rng;

    const next = duelReducer(choose, { type: 'CANNON_SELECTED', cannonId: 'swivel_gun' });

    expect(next.phase).toBe('reload');
    if (next.phase !== 'reload') return;
    expect(next.cannonId).toBe('swivel_gun');
    expect(next.timerMs).toBe(getCannon('swivel_gun').timerMs);
    expect(next.question.choices).toHaveLength(4);
    const values = next.question.choices.map((c) => c.value);
    expect(new Set(values).size, 'four distinct choice values').toBe(4);
    expect(next.recentTemplateIds[0]).toBe(next.question.templateId);
    expect(next.rng).not.toEqual(rngBefore);
    expect(next.rng.state).not.toBe(rngBefore.state);
  });

  it('spec(T-020:AC-3) CANNON_SELECTED outside playerLoadout is a reference no-op', () => {
    const choose = duelReducer(createDuelState(baseConfig(3)), { type: 'ANIMATION_DONE' });
    const next = duelReducer(choose, { type: 'CANNON_SELECTED', cannonId: 'long_nine' });
    expect(next).toBe(choose);
  });

  it('spec(T-020:AC-12) resolvePlayer with both hulls > 0 + ANIMATION_DONE → rivalTurn, turnToken++, volley unchanged', () => {
    const start = resolvePlayerState({
      enemyHull: 20,
      playerHull: 80,
      turnToken: 5,
      volleyNumber: 3,
    });
    const next = duelReducer(start, { type: 'ANIMATION_DONE' });

    expect(next.phase).toBe('rivalTurn');
    expect(next.turnToken).toBe(6);
    expect(next.volleyNumber).toBe(3);
  });

  it('spec(T-020:AC-15) resolveRival with both hulls > 0 + ANIMATION_DONE → playerChoose, volley++ and turnToken++', () => {
    const start = resolveRivalState({
      enemyHull: 20,
      playerHull: 80,
      turnToken: 5,
      volleyNumber: 3,
    });
    const next = duelReducer(start, { type: 'ANIMATION_DONE' });

    expect(next.phase).toBe('playerChoose');
    expect(next.volleyNumber).toBe(4);
    expect(next.turnToken).toBe(6);
  });
});

// =============================================================================================
// AC-4…AC-9 — answer / timeout / perfect / temperament matrix
// =============================================================================================

describe('T-020 duelReducer — answer resolution', () => {
  it('spec(T-020:AC-4) correct ANSWER_CHOSEN at 90% timer → resolvePlayer volley, hull/tally/log update', () => {
    const start = reloadState({
      cannonId: 'swivel_gun',
      enemyHull: 40,
      playerHull: PLAYER_HULL,
      tally: { correctAnswers: 0, totalAnswers: 0, perfectShots: 0, bySkill: {} },
      actionLog: [],
      rng: createRng(99),
    });
    const elapsedMs = Math.round(0.9 * start.timerMs);
    const [expectedOutcome] = resolveShot({
      cannon: getCannon('swivel_gun'),
      correct: true,
      elapsedMs,
      rng: start.rng,
    });

    const next = duelReducer(start, {
      type: 'ANSWER_CHOSEN',
      choiceIndex: start.question.correctIndex,
      elapsedMs,
    });

    expect(next.phase).toBe('resolvePlayer');
    if (next.phase !== 'resolvePlayer') return;
    expect(next.outcome.kind).toBe('volley');
    expect(next.outcome).toEqual(expectedOutcome);
    expect(next.enemyHull).toBe(start.enemyHull - expectedOutcome.damageToEnemy);
    expect(next.tally.correctAnswers).toBe(1);
    expect(next.tally.totalAnswers).toBe(1);
    expect(next.actionLog).toHaveLength(1);
    expect(next.actionLog[0]).toEqual({
      actor: 'player',
      cannonId: 'swivel_gun',
      correct: true,
      elapsedMs,
    });
  });

  it('spec(T-020:AC-5) wrong answer on volatile → misfire, recoil on player, tally attempts only', () => {
    const start = reloadState({
      cannonId: 'double_broadside',
      question: {
        ...FIXTURE_QUESTION,
        skill: 'two_step_add_sub',
        templateId: 'two_step_add_sub__fixture',
      },
      enemyHull: 40,
      playerHull: 50,
      tally: { correctAnswers: 2, totalAnswers: 3, perfectShots: 0, bySkill: {} },
      actionLog: [],
      rng: createRng(50),
    });
    const elapsedMs = 4000;
    const recoil = getCannon('double_broadside').recoilDamage;
    expect(recoil).toBeGreaterThan(0);
    const [expectedOutcome] = resolveShot({
      cannon: getCannon('double_broadside'),
      correct: false,
      elapsedMs,
      rng: start.rng,
    });

    const next = duelReducer(start, {
      type: 'ANSWER_CHOSEN',
      choiceIndex: wrongIndex(start.question),
      elapsedMs,
    });

    expect(next.phase).toBe('resolvePlayer');
    if (next.phase !== 'resolvePlayer') return;
    expect(next.outcome.kind).toBe('misfire');
    expect(next.outcome).toEqual(expectedOutcome);
    expect(next.enemyHull).toBe(40);
    expect(next.playerHull).toBe(50 - expectedOutcome.damageToSelf);
    expect(next.playerHull).toBe(50 - recoil);
    expect(next.tally.totalAnswers).toBe(4);
    expect(next.tally.correctAnswers).toBe(2);
    expect(next.actionLog).toHaveLength(1);
    expect(next.actionLog[0]?.correct).toBe(false);
    expect(next.actionLog[0]?.actor).toBe('player');
  });

  it('spec(T-020:AC-6) wrong answer on reliable → both hulls unchanged, phase resolvePlayer', () => {
    const start = reloadState({
      cannonId: 'swivel_gun',
      enemyHull: 40,
      playerHull: 50,
      rng: createRng(51),
    });

    const next = duelReducer(start, {
      type: 'ANSWER_CHOSEN',
      choiceIndex: wrongIndex(start.question),
      elapsedMs: 4000,
    });

    expect(next.phase).toBe('resolvePlayer');
    expect(next.playerHull).toBe(50);
    expect(next.enemyHull).toBe(40);
  });

  it('spec(T-020:AC-7) TIMER_EXPIRED deeply equals wrong ANSWER_CHOSEN at elapsedMs === timerMs', () => {
    const start = reloadState({
      cannonId: 'swivel_gun',
      enemyHull: 40,
      playerHull: 50,
      tally: { correctAnswers: 0, totalAnswers: 0, perfectShots: 0, bySkill: {} },
      actionLog: [],
      rng: createRng(52),
    });
    // Same starting state object must not be shared — clone via JSON so each path starts equal.
    const forTimeout = JSON.parse(JSON.stringify(start)) as typeof start;
    const forWrong = JSON.parse(JSON.stringify(start)) as typeof start;

    const viaTimeout = duelReducer(forTimeout, { type: 'TIMER_EXPIRED' });
    const viaWrong = duelReducer(forWrong, {
      type: 'ANSWER_CHOSEN',
      choiceIndex: wrongIndex(forWrong.question),
      elapsedMs: forWrong.timerMs,
    });

    expect(viaTimeout).toEqual(viaWrong);
    if (viaTimeout.phase === 'resolvePlayer') {
      expect(viaTimeout.actionLog[0]?.elapsedMs).toBe(start.timerMs);
    }
    if (viaWrong.phase === 'resolvePlayer') {
      expect(viaWrong.actionLog[0]?.elapsedMs).toBe(start.timerMs);
    }
  });

  it('spec(T-020:AC-8) ANSWER_CHOSEN with out-of-range choiceIndex or negative elapsedMs is a reference no-op', () => {
    const start = reloadState();

    expect(duelReducer(start, { type: 'ANSWER_CHOSEN', choiceIndex: -1, elapsedMs: 100 })).toBe(start);
    expect(duelReducer(start, { type: 'ANSWER_CHOSEN', choiceIndex: 4, elapsedMs: 100 })).toBe(start);
    expect(duelReducer(start, { type: 'ANSWER_CHOSEN', choiceIndex: 99, elapsedMs: 100 })).toBe(start);
    expect(duelReducer(start, { type: 'ANSWER_CHOSEN', choiceIndex: 0, elapsedMs: -1 })).toBe(start);
  });

  it('spec(T-020:AC-9) correct answer inside perfect window → perfectShot, tally, ballCount', () => {
    const start = reloadState({
      cannonId: 'swivel_gun',
      tally: { correctAnswers: 0, totalAnswers: 0, perfectShots: 0, bySkill: {} },
      rng: createRng(53),
    });
    const boundary = PERFECT_SHOT_TIMER_FRACTION * start.timerMs;
    const elapsedMs = boundary - 1;
    expect(elapsedMs).toBeLessThan(boundary);
    const [expectedOutcome] = resolveShot({
      cannon: getCannon('swivel_gun'),
      correct: true,
      elapsedMs,
      rng: start.rng,
    });

    const next = duelReducer(start, {
      type: 'ANSWER_CHOSEN',
      choiceIndex: start.question.correctIndex,
      elapsedMs,
    });

    expect(next.phase).toBe('resolvePlayer');
    if (next.phase !== 'resolvePlayer') return;
    expect(next.outcome).toEqual(expectedOutcome);
    expect(next.outcome.perfectShot).toBe(true);
    expect(next.tally.perfectShots).toBe(1);
    expect(next.outcome.ballCount).toBe(BASE_BALLS_PER_VOLLEY + 1);
  });
});

// =============================================================================================
// AC-10, AC-11, AC-23 — terminals and clamping
// =============================================================================================

describe('T-020 duelReducer — terminals and hull clamp', () => {
  it('spec(T-020:AC-10) resolvePlayer with enemyHull <= 0 + ANIMATION_DONE → victory result', () => {
    const tally = {
      correctAnswers: 4,
      totalAnswers: 4,
      perfectShots: 2,
      bySkill: { add_within_10: { correct: 4, attempts: 4 } },
    };
    const start = resolvePlayerState({
      enemyHull: 0,
      playerHull: 60,
      volleyNumber: 4,
      tally,
      actionLog: [],
    });

    const next = duelReducer(start, { type: 'ANIMATION_DONE' });

    expect(next.phase).toBe('victory');
    if (next.phase !== 'victory') return;
    expect(next.result.won).toBe(true);
    expect(next.result.tally).toEqual(tally);
    expect(next.result.volleys).toBe(4);
    expect(next.enemyHull).toBe(0);
  });

  it('spec(T-020:AC-11) resolvePlayer after volatile recoil to 0 + ANIMATION_DONE → defeat', () => {
    const start = resolvePlayerState({
      cannonId: 'double_broadside',
      enemyHull: 30,
      playerHull: 0,
      outcome: resolveShot({
        cannon: getCannon('double_broadside'),
        correct: false,
        elapsedMs: 1000,
        rng: createRng(8),
      })[0],
    });

    const next = duelReducer(start, { type: 'ANIMATION_DONE' });

    expect(next.phase).toBe('defeat');
    if (next.phase !== 'defeat') return;
    expect(next.result.won).toBe(false);
    expect(next.playerHull).toBe(0);
  });

  it('spec(T-020:AC-11) resolveRival with playerHull <= 0 + ANIMATION_DONE → defeat', () => {
    const tally = {
      correctAnswers: 2,
      totalAnswers: 3,
      perfectShots: 0,
      bySkill: { add_within_10: { correct: 2, attempts: 3 } },
    };
    const start = resolveRivalState({
      enemyHull: 28,
      playerHull: 0,
      volleyNumber: 3,
      damageToPlayer: 12,
      tally,
    });

    const next = duelReducer(start, { type: 'ANIMATION_DONE' });

    expect(next.phase).toBe('defeat');
    if (next.phase !== 'defeat') return;
    expect(next.result.won).toBe(false);
    expect(next.result.tally).toEqual(tally);
    expect(next.result.volleys).toBe(3);
    expect(next.playerHull).toBe(0);
    expect(next.enemyHull).toBe(28);
  });

  it('spec(T-020:AC-10) resolveRival with enemyHull <= 0 + ANIMATION_DONE → victory', () => {
    const tally = {
      correctAnswers: 4,
      totalAnswers: 4,
      perfectShots: 1,
      bySkill: { add_within_10: { correct: 4, attempts: 4 } },
    };
    // Enemy-first terminal order: even with playerHull already 0, enemyHull <= 0 wins.
    // The pure continue-symmetric case keeps playerHull > 0.
    const start = resolveRivalState({
      enemyHull: 0,
      playerHull: 40,
      volleyNumber: 4,
      damageToPlayer: 0,
      tally,
    });

    const next = duelReducer(start, { type: 'ANIMATION_DONE' });

    expect(next.phase).toBe('victory');
    if (next.phase !== 'victory') return;
    expect(next.result.won).toBe(true);
    expect(next.result.tally).toEqual(tally);
    expect(next.result.volleys).toBe(4);
    expect(next.enemyHull).toBe(0);
  });

  it('spec(T-020:AC-23) overkill clamps at damage application (resolvePlayer / resolveRival), not at terminal', () => {
    const playerReload = reloadState({
      cannonId: 'swivel_gun',
      enemyHull: 5,
      playerHull: 80,
      rng: createRng(60),
      tally: { correctAnswers: 0, totalAnswers: 0, perfectShots: 0, bySkill: {} },
      actionLog: [],
    });
    const [expected] = resolveShot({
      cannon: getCannon('swivel_gun'),
      correct: true,
      elapsedMs: PERFECT_ELAPSED_MS,
      rng: playerReload.rng,
    });
    expect(expected.damageToEnemy).toBeGreaterThan(5);

    const afterPlayer = duelReducer(playerReload, {
      type: 'ANSWER_CHOSEN',
      choiceIndex: playerReload.question.correctIndex,
      elapsedMs: PERFECT_ELAPSED_MS,
    });
    expect(afterPlayer.phase).toBe('resolvePlayer');
    expect(afterPlayer.enemyHull).toBe(0);
    expect(afterPlayer.enemyHull).toBeGreaterThanOrEqual(0);

    const rivalStart = rivalTurnState({
      playerHull: 3,
      enemyHull: 40,
      rng: createRng(61),
      actionLog: [],
      tally: { correctAnswers: 1, totalAnswers: 1, perfectShots: 0, bySkill: {} },
    });
    const rivalVolley: RivalVolley = {
      cannonId: 'six_pounder',
      correct: true,
      elapsedMs: PERFECT_ELAPSED_MS,
    };
    const [rivalOutcome] = resolveShot({
      cannon: getCannon('six_pounder'),
      correct: true,
      elapsedMs: PERFECT_ELAPSED_MS,
      rng: rivalStart.rng,
    });
    expect(rivalOutcome.damageToEnemy).toBeGreaterThan(3);

    const afterRival = duelReducer(rivalStart, { type: 'RIVAL_ACTION', volley: rivalVolley });
    expect(afterRival.phase).toBe('resolveRival');
    expect(afterRival.playerHull).toBe(0);
    expect(afterRival.playerHull).toBeGreaterThanOrEqual(0);
  });
});

// =============================================================================================
// AC-13, AC-14 — rival turn
// =============================================================================================

describe('T-020 duelReducer — rival turn', () => {
  it('spec(T-020:AC-13) correct RIVAL_ACTION → resolveRival, damages player, logs rival, tally unchanged', () => {
    const start = rivalTurnState({
      playerHull: 80,
      tally: { correctAnswers: 2, totalAnswers: 3, perfectShots: 1, bySkill: {} },
      actionLog: [{ actor: 'player', cannonId: 'swivel_gun', correct: true, elapsedMs: 900 }],
      rng: createRng(70),
    });
    const volley: RivalVolley = {
      cannonId: 'six_pounder',
      correct: true,
      elapsedMs: 1200,
    };
    const [outcome] = resolveShot({
      cannon: getCannon('six_pounder'),
      correct: true,
      elapsedMs: 1200,
      rng: start.rng,
    });

    const next = duelReducer(start, { type: 'RIVAL_ACTION', volley });

    expect(next.phase).toBe('resolveRival');
    if (next.phase !== 'resolveRival') return;
    expect(next.playerHull).toBe(start.playerHull - outcome.damageToEnemy);
    expect(next.damageToPlayer).toBe(outcome.damageToEnemy);
    expect(next.actionLog).toHaveLength(2);
    expect(next.actionLog[1]).toEqual({
      actor: 'rival',
      cannonId: volley.cannonId,
      correct: volley.correct,
      elapsedMs: volley.elapsedMs,
    });
    expect(next.tally.totalAnswers).toBe(3);
    expect(next.tally.correctAnswers).toBe(2);
  });

  it('spec(T-020:AC-14) RIVAL_ACTION naming a cannon outside rivalLoadout is a reference no-op', () => {
    const start = rivalTurnState();
    const next = duelReducer(start, {
      type: 'RIVAL_ACTION',
      volley: { cannonId: 'long_nine', correct: true, elapsedMs: 500 },
    });
    expect(next).toBe(start);
  });
});

// =============================================================================================
// AC-16, AC-17 — exhaustive no-ops and frozen terminals
// =============================================================================================

describe('T-020 duelReducer — no-op contract', () => {
  it('spec(T-020:AC-16) dod(T-020:5) exhaustive 8×5 out-of-phase matrix returns identical references', () => {
    const states = stateByPhase();
    const events = sampleEvents();

    for (const phase of EXPECTED_PHASES) {
      const state = states[phase];
      const allowed = new Set(IN_PHASE_EVENTS[phase]);
      for (const eventType of EXPECTED_EVENT_TYPES) {
        if (allowed.has(eventType)) continue;
        const result = duelReducer(state, events[eventType]);
        expect(result, `${phase} + ${eventType} must be reference-identical`).toBe(state);
      }
    }
  });

  it('spec(T-020:AC-17) victory and defeat ignore every event (frozen duel)', () => {
    const states = stateByPhase();
    const events = sampleEvents();

    for (const phase of ['victory', 'defeat'] as const) {
      const state = states[phase];
      for (const eventType of EXPECTED_EVENT_TYPES) {
        expect(duelReducer(state, events[eventType]), `${phase} + ${eventType}`).toBe(state);
      }
    }
  });
});

// =============================================================================================
// AC-18…AC-20 — scripted duel, determinism, mid-duel serialisation
// =============================================================================================

describe('T-020 duelReducer — scripted duel paths', () => {
  it('spec(T-020:AC-18) four correct player volleys vs port_sumwich hull → victory, alternating log', () => {
    expect(ENEMY_HULL_BY_ISLAND.port_sumwich).toBe(45);
    const end = driveScriptedDuel();

    expect(end.phase).toBe('victory');
    if (end.phase !== 'victory') return;
    expect(end.result.won).toBe(true);
    expect(end.result.volleys).toBe(4);
    expect(end.enemyHull).toBe(0);
    expect(end.playerHull).toBe(PLAYER_HULL);

    const actors = end.actionLog.map((e) => e.actor);
    expect(actors).toEqual(['player', 'rival', 'player', 'rival', 'player', 'rival', 'player']);
    expect(end.actionLog.filter((e) => e.actor === 'player')).toHaveLength(4);
    expect(end.actionLog.filter((e) => e.actor === 'rival')).toHaveLength(3);
  });

  it('spec(T-020:AC-19) same config + event sequence replayed 20× → identical final states', () => {
    const finals: DuelState[] = [];
    for (let i = 0; i < 20; i += 1) {
      finals.push(driveScriptedDuel());
    }
    for (let i = 1; i < finals.length; i += 1) {
      expect(finals[i]).toEqual(finals[0]);
    }
  });

  it('spec(T-020:AC-20) JSON round-trip of any mid-duel state then next event matches live path', () => {
    // Walk the live path, and at every reachable pre-event state verify round-trip + next event.
    let live: DuelState = createDuelState(baseConfig(SCRIPTED_DUEL_SEED));
    const plan: DuelEvent[] = [];

    // Build the full event list by probing questions as we go on a dry run first.
    {
      let s: DuelState = createDuelState(baseConfig(SCRIPTED_DUEL_SEED));
      const push = (e: DuelEvent): void => {
        plan.push(e);
        s = duelReducer(s, e);
      };
      push({ type: 'ANIMATION_DONE' });
      for (let volley = 1; volley <= 4; volley += 1) {
        push({ type: 'CANNON_SELECTED', cannonId: 'swivel_gun' });
        if (s.phase !== 'reload') throw new Error('expected reload');
        push({
          type: 'ANSWER_CHOSEN',
          choiceIndex: s.question.correctIndex,
          elapsedMs: PERFECT_ELAPSED_MS,
        });
        push({ type: 'ANIMATION_DONE' });
        if (volley < 4) {
          push({
            type: 'RIVAL_ACTION',
            volley: {
              cannonId: 'six_pounder',
              correct: false,
              elapsedMs: RIVAL_MISS_ELAPSED_MS,
            },
          });
          push({ type: 'ANIMATION_DONE' });
        }
      }
    }

    for (let i = 0; i < plan.length; i += 1) {
      const event = plan[i]!;
      const viaLive = duelReducer(live, event);
      const revived = JSON.parse(JSON.stringify(live)) as DuelState;
      const viaRoundTrip = duelReducer(revived, event);
      expect(viaRoundTrip, `step ${i} ${event.type}`).toEqual(viaLive);
      live = viaLive;
    }
  });
});

// =============================================================================================
// AC-21 — loud config failure
// =============================================================================================

describe('T-020 duelReducer — configuration errors', () => {
  it('spec(T-020:AC-21) CANNON_SELECTED with no templates for skill throws QuestionGenerationError NO_TEMPLATE', () => {
    const choose = duelReducer(
      createDuelState({
        ...baseConfig(21),
        templatesBySkill: {}, // no add_within_10 pool
      }),
      { type: 'ANIMATION_DONE' },
    );
    expect(choose.phase).toBe('playerChoose');

    expect(() => duelReducer(choose, { type: 'CANNON_SELECTED', cannonId: 'swivel_gun' })).toThrow(
      QuestionGenerationError,
    );
    try {
      duelReducer(choose, { type: 'CANNON_SELECTED', cannonId: 'swivel_gun' });
      expect.fail('expected throw');
    } catch (error) {
      expect(error).toBeInstanceOf(QuestionGenerationError);
      expect((error as QuestionGenerationError).code).toBe('NO_TEMPLATE');
    }
  });
});

// =============================================================================================
// AC-22 — non-mutation
// =============================================================================================

describe('T-020 duelReducer — purity / immutability', () => {
  it('spec(T-020:AC-22) every table transition leaves the input object and its arrays unmutated', () => {
    const reloadForAnswer = toReload(23, 'swivel_gun');
    const reloadForTimeout = toReload(24, 'swivel_gun');
    const transitions: readonly { readonly state: DuelState; readonly event: DuelEvent }[] = [
      {
        state: createDuelState(baseConfig(22)),
        event: { type: 'ANIMATION_DONE' },
      },
      {
        state: duelReducer(createDuelState(baseConfig(22)), { type: 'ANIMATION_DONE' }),
        event: { type: 'CANNON_SELECTED', cannonId: 'swivel_gun' },
      },
      {
        state: reloadForAnswer,
        event: {
          type: 'ANSWER_CHOSEN',
          choiceIndex: reloadForAnswer.question.correctIndex,
          elapsedMs: 5000,
        },
      },
      {
        state: reloadForTimeout,
        event: { type: 'TIMER_EXPIRED' },
      },
      {
        state: resolvePlayerState({ enemyHull: 20, playerHull: 80 }),
        event: { type: 'ANIMATION_DONE' },
      },
      {
        state: rivalTurnState({ rng: createRng(25) }),
        event: {
          type: 'RIVAL_ACTION',
          volley: { cannonId: 'six_pounder', correct: false, elapsedMs: 1000 },
        },
      },
      {
        state: resolveRivalState({ enemyHull: 20, playerHull: 80 }),
        event: { type: 'ANIMATION_DONE' },
      },
    ];

    for (const { state, event } of transitions) {
      const jsonBefore = JSON.stringify(state);
      const arrays = snapshotArrays(state);

      const next = duelReducer(state, event);
      expect(next, `${state.phase} + ${event.type}`).not.toBe(state);
      expect(JSON.stringify(state), `${state.phase} input mutated`).toBe(jsonBefore);
      expect(state.playerLoadout).toBe(arrays.playerLoadout);
      expect(state.rivalLoadout).toBe(arrays.rivalLoadout);
      expect(state.recentTemplateIds).toBe(arrays.recentTemplateIds);
      expect(state.actionLog).toBe(arrays.actionLog);
      if (state.phase === 'reload' && arrays.choices) {
        expect(state.question.choices).toBe(arrays.choices);
      }
    }
  });
});

// =============================================================================================
// AC-24 — literal enumerations in THIS file
// =============================================================================================

describe('T-020 duelReducer — test-file structure', () => {
  it('spec(T-020:AC-24) phase and event enumerations are hardcoded literals, not derived', () => {
    const literalBlock = (name: string): readonly string[] => {
      const match = new RegExp(`const ${name} = \\[([^\\]]*)\\] as const;`).exec(OWN_SOURCE);
      expect(match, `${name} must be an inline array literal ending in "as const"`).not.toBeNull();
      return (match?.[1] ?? '')
        .split(',')
        .map((line) => line.trim())
        .filter((line) => line.length > 0);
    };

    const phaseEntries = literalBlock('EXPECTED_PHASES');
    const eventEntries = literalBlock('EXPECTED_EVENT_TYPES');

    for (const entry of [...phaseEntries, ...eventEntries]) {
      expect(entry).toMatch(/^'[A-Za-z_]+'$/);
    }
    expect(phaseEntries.map((e) => e.slice(1, -1))).toEqual([...EXPECTED_PHASES]);
    expect(eventEntries.map((e) => e.slice(1, -1))).toEqual([...EXPECTED_EVENT_TYPES]);

    // No derivation from the production exports.
    expect(OWN_SOURCE).not.toMatch(/EXPECTED_PHASES\s*=\s*DUEL_PHASES/);
    expect(OWN_SOURCE).not.toMatch(/EXPECTED_PHASES\s*=\s*\[\s*\.\.\.DUEL_PHASES/);
    expect(OWN_SOURCE).not.toMatch(/EXPECTED_EVENT_TYPES\s*=\s*\[.*DuelEvent/);
    expect(OWN_SOURCE.includes('DUEL_PHASES.map')).toBe(false);
  });
});

// =============================================================================================
// Definition of Done
// =============================================================================================

describe('T-020 Definition of Done', () => {
  it('dod(T-020:1) tags a test against every acceptance criterion the ticket declares', () => {
    const declared = [...TICKET_SOURCE.matchAll(/\*\*(AC-\d+)\*\*/g)].map((match) => match[1]);
    const unique = [...new Set(declared)];
    const untagged = unique.filter((ac) => !OWN_SOURCE.includes(`spec(T-020:${ac})`));

    expect(unique.length).toBe(24);
    expect(untagged).toEqual([]);
  });

  it('dod(T-020:2) keeps local gates wired and this suite free of skip/only markers', () => {
    const gates = readFileSync(join(REPO_ROOT, '.tdd-swarm/run-local-gates.sh'), 'utf8');
    for (const command of ['prettier --check', 'eslint . --max-warnings 0', 'tsc --noEmit', 'vitest run']) {
      expect(gates, `run-local-gates.sh must still run: ${command}`).toContain(command);
    }
    for (const marker of DEFERRED_WORK_MARKERS) {
      expect(OWN_SOURCE.includes(marker), `suite must not contain ${marker}`).toBe(false);
    }
    expect(FOCUSED_TEST_PATTERN.test(OWN_SOURCE)).toBe(false);
  });

  it('dod(T-020:3) numbers every dod tag so spec-lint covers all eight DoD items', () => {
    const dodCount = (TICKET_SOURCE.match(/^- \[[ x]\] /gm) ?? []).length;
    const tagged = [...OWN_SOURCE.matchAll(/dod\(T-020:([^)]*)\)/g)].map((match) => match[1] ?? '');
    const unparseable = tagged.filter((id) => !/^\d+$/.test(id));
    const covered = new Set(tagged.filter((id) => /^\d+$/.test(id)).map(Number));
    const missing = Array.from({ length: dodCount }, (_, i) => i + 1).filter((n) => !covered.has(n));

    expect(dodCount).toBe(8);
    expect(unparseable).toEqual([]);
    expect(missing).toEqual([]);
    expect(OWN_SOURCE).toContain('spec(T-020:AC-');
  });

  it('dod(T-020:4) duelReducer is a two-arg pure sync function with no Math.random/Date/await/React', () => {
    expect(typeof duelReducer).toBe('function');
    expect(duelReducer.length).toBe(2);

    expect(existsSync(REDUCER_SRC_PATH)).toBe(true);
    const source = readFileSync(REDUCER_SRC_PATH, 'utf8');
    expect(source).not.toMatch(/\bMath\.random\b/);
    expect(source).not.toMatch(/\bDate\b/);
    expect(source).not.toMatch(/\bawait\b/);
    expect(source).not.toMatch(/from ['"]react['"]/);
    expect(source).not.toMatch(/from ['"]react\//);
  });

  it('dod(T-020:6) hulls clamp at apply-time and tally counts player answers only', () => {
    // Behaviour is pinned by AC-13 + AC-23; this DoD tag keeps spec-lint coverage honest.
    expect(OWN_SOURCE).toContain('spec(T-020:AC-13)');
    expect(OWN_SOURCE).toContain('spec(T-020:AC-23)');
  });

  it('dod(T-020:7) damage flows through @engine/duel/damage — no local damage arithmetic', () => {
    expect(existsSync(REDUCER_SRC_PATH)).toBe(true);
    const source = readFileSync(REDUCER_SRC_PATH, 'utf8');
    expect(source).toMatch(/resolveShot/);
    expect(source).toMatch(/@engine\/duel\/damage/);
    expect(source).not.toMatch(/damageMin\s*\*|damageMax\s*\*/);
    expect(source).not.toMatch(/PERFECT_SHOT_BONUS_DAMAGE/);
    expect(source).not.toMatch(/ANSWER_QUALITY_FLOOR/);
  });

  it('dod(T-020:8) production file for this ticket is src/engine/duel/reducer.ts', () => {
    expect(existsSync(REDUCER_SRC_PATH), 'implementer must create reducer.ts').toBe(true);
    const present = readdirSync(DUEL_DIR)
      .filter((name) => name.endsWith('.ts'))
      .sort();
    // Prior tickets own types.ts + damage.ts; this ticket adds exactly reducer.ts.
    expect(present).toEqual(['damage.ts', 'reducer.ts', 'types.ts']);
  });
});
